import Database from 'better-sqlite3';
import path from 'path';

// SQLite database — /tmp is the only writable directory on Vercel serverless functions
const DB_PATH = process.env.NODE_ENV === 'production'
  ? '/tmp/data.db'
  : path.join(process.cwd(), 'data.db');

// Lazy-initialize so the DB isn't opened at build time
let _db: Database.Database | null = null;
function db(): Database.Database {
  if (!_db) {
    _db = new Database(DB_PATH);
    _db.exec(`
      CREATE TABLE IF NOT EXISTS sessions (
        id               TEXT PRIMARY KEY,
        created_at       TEXT NOT NULL,
        startup_name     TEXT NOT NULL,
        industry         TEXT NOT NULL,
        target_audience  TEXT NOT NULL,
        creator_requirements TEXT NOT NULL,
        creators         TEXT NOT NULL,
        creator_ratings  TEXT NOT NULL
      )
    `);
  }
  return _db;
}

// All the fields a creator card will have, populated by Andy
export type Creator = {
  id: string;
  name: string;
  niche: string;
  platform: string;
  follower_range: string;
  one_liner: string;
  why_fit: string;
  match_score: number;
};

// All the fields required and related to Andy scoring a creator match
export type CreatorRating = {
  // How good of a match and why, determined by Andy
  matchPercent: number;
  reason: string;
  one_liner: string;
  why_fit: string;
  // Profile fields Andy generates
  name: string;
  age: number;
  handle: string;
  platform: string;
  secondary_platform?: string;
  tertiary_platform?: string;
  niche: string;
  secondary_niche?: string;
  tertiary_niche?: string;
  audience: string;
};

// Session object generated by input form prompts and what Andy thinks will be best for it
export type Session = {
  // UUID and timestamp
  id: string;
  created_at: string;
  // Input form
  startup_name: string;
  industry: string;
  target_audience: string;
  creator_requirements: string;
  // Andy's take on what a good creator will be, using the creator's image path as the key
  creators: Creator[];
  creator_ratings: Record<string, CreatorRating>;
};

// SQLite rows store creators and creator_ratings as JSON strings
type SessionRow = Omit<Session, 'creators' | 'creator_ratings'> & {
  creators: string;
  creator_ratings: string;
};

function rowToSession(row: SessionRow): Session {
  return {
    ...row,
    creators: JSON.parse(row.creators),
    creator_ratings: JSON.parse(row.creator_ratings),
  };
}

// List all sessions, sorted from newest to oldest
export function listSessions(): Session[] {
  const rows = db()
    .prepare('SELECT * FROM sessions ORDER BY created_at DESC')
    .all() as SessionRow[];
  return rows.map(rowToSession);
}

// Finds a single session by UUID
export function getSession(id: string): Session | null {
  const row = db()
    .prepare('SELECT * FROM sessions WHERE id = ?')
    .get(id) as SessionRow | undefined;
  return row ? rowToSession(row) : null;
}

// Inserts a new session
export function createSession(session: Session): Session {
  db().prepare(`
    INSERT INTO sessions (id, created_at, startup_name, industry, target_audience, creator_requirements, creators, creator_ratings)
    VALUES (@id, @created_at, @startup_name, @industry, @target_audience, @creator_requirements, @creators, @creator_ratings)
  `).run({
    ...session,
    creators: JSON.stringify(session.creators),
    creator_ratings: JSON.stringify(session.creator_ratings),
  });
  return session;
}

// Remove a specific session
export function deleteSession(id: string): boolean {
  const result = db().prepare('DELETE FROM sessions WHERE id = ?').run(id);
  return result.changes > 0;
}
