import fs from 'fs';
import path from 'path';

// Flat JSON database stored at the project root.
const DB_PATH = path.join(process.cwd(), 'data.json');

// All the fields a creator card will have, populated by Andy
export type Creator = {
  id: string;
  name: string;
  niche: string;
  platform: string;
  follower_range: string;
  one_liner: string;
  why_fit: string;
  match_score: number;
};

// All the fields required and related to Andy scoring a creator match
export type CreatorRating = {
  // How good of a match and why, determined by Andy
  matchPercent: number;
  reason: string;
  // Profile fields Andy generates
  name: string;
  age: number;
  handle: string;
  platforms: string[];
  niche: string;
  audience: string;
};

// Session object generated by input form prompts and what Andy thinks will be best for it
export type Session = {
  // UUID and timestamp
  id: string;
  created_at: string; 
  // Input form
  startup_name: string;
  industry: string;
  target_audience: string;
  creator_requirements: string;
  // Andy's take on what a good creator will be, using the creator's image path as the key
  creators: Creator[];
  creator_ratings: Record<string, CreatorRating>;
};

// Main Session object
type Store = { sessions: Session[] };

// Check if session file exists and load it
function read(): Store {
  if (!fs.existsSync(DB_PATH)) return { sessions: [] };
  return JSON.parse(fs.readFileSync(DB_PATH, 'utf-8')) as Store;
}

// Write session data
function write(store: Store) {
  fs.writeFileSync(DB_PATH, JSON.stringify(store, null, 2), 'utf-8');
}

// List all sessions, sorted from newest to oldest
export function listSessions(): Session[] {
  return read().sessions.slice().sort(
    (a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  );
}

// Finds a single session by UUID
export function getSession(id: string): Session | null {
  return read().sessions.find((s) => s.id === id) ?? null;
}

// Appends a new session and writes to disk
export function createSession(session: Session): Session {
  const store = read();
  store.sessions.push(session);
  write(store);
  return session;
}

// Update Creator Ratings for a specific session
export function updateSessionRatings(id: string, ratings: Record<string, CreatorRating>): void {
  const store = read();
  const session = store.sessions.find((s) => s.id === id);
  if (session) {
    session.creator_ratings = ratings;
    write(store);
  }
}

// Remove a specific session
export function deleteSession(id: string): boolean {
  const store = read();
  const before = store.sessions.length;
  store.sessions = store.sessions.filter((s) => s.id !== id);
  if (store.sessions.length === before) return false;
  write(store);
  return true;
}
